John Razel
aclc-iriga-wad1-2024/wad1-2024-09-01 pull request #17
Opened 2024-09-09 15:06 UTC by razsopogi

2024-09-09 15:07 UTC, razsopogi commented
sir okay na po?

2024-09-10 00:11 UTC, kulotsystems requested changes
@razsopogi please undo all the changes you made to the _template folder.
If I mege it, then the template will already contain your changes.

2024-09-10 08:55 UTC, razsopogi commented
sir binalik kona po sa dati yung _template, ano na po next kong gagawin?

2024-09-10 09:06 UTC, razsopogi commented
ni update ko nalang po sir yung _template

2024-09-10 09:07 UTC, razsopogi commented
hindi po kasi ako maka gawa ng maayos dito sa laptop kasi masyado po kasing ma hang tyaka ang tagal pa po mag boot, kelangan pa i upgrade

2024-09-10 11:17 UTC, kulotsystems approved these changes
All good @razsopogi.

2024-09-10 11:17 UTC, merged